### ISSUE TITLE
daux.io domain serves old docs and points to old repo

### ISSUE THREAD

**Issue by vassudanagunta** [dauxio/dauxio.github.io#2]
Easy fix: Set up `daux.io` as a custom domain for the `dauxio.github.io` GitHub Pages site. 

See [Using a custom domain with GitHub Pages](https://help.github.com/articles/using-a-custom-domain-with-github-pages/).

Afterwards you can delete/turn off whatever is currently serving the outdated site.

**Comment by onigoetz** [comment]
Hello,

I know how to setup a custom domain, the issue is that the domain doesn't belong to me :) and the owner of the domain ( @justinwalsh ) doesn't reply to emails or anything.

**Comment by justinwalsh** [comment]
This has been fixed. Sorry it took so long.
