### ISSUE TITLE
Header issue at narrow width

### ISSUE THREAD

**Issue by plfstr** [dauxio/dauxio.github.io#3]
There is an issue with narrow screen widths (<360px) and the header. In `.Navbar`, the search bar jumps down below the logo and squashes the `.Homepage` content below to the left.

I believe its a float issue, along with set height.

Something like the following is needed:
```
.Navbar {
    /*height: 50px */
    overflow: auto;
}
```

**Comment by onigoetz** [comment]
Hi, thanks for the report, this was fixed by https://github.com/dauxio/daux.io/pull/391
